
[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ["setuptools>=58.1.0","wheel >= 0.31.0","twine >= 1.11.0"]
build-backend = "setuptools.build_meta"
